spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/citi?useUnicode=true&useSSL=false&characterEncoding=utf8
        username: chldu
        password: rH@ps0dydb